services:
  fauthless-go:
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: Dockerfile.example
    image: fauthless-go
    hostname: "fauthless-go"
    container_name: "fauthless-go"
    env_file:
      - .env.example
    ports:
      - "${COOKIE_PORT:-8000}:${COOKIE_PORT:-8000}"
    networks:
      - golang

  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example
    ports:
      - "5432:5432"
    networks:
      - golang

volumes:
  postgres_data:

networks:
  golang:
